-- Corpus import observability.
create table if not exists public.lexicon_import_runs(
 id bigint generated by default as identity primary key,
 source_key text not null references public.lexicon_sources(key),
 started_at timestamptz not null default now(),finished_at timestamptz,
 candidates integer not null default 0,ready integer not null default 0,rejected integer not null default 0,notes text
);
alter table public.lexicon_import_runs enable row level security;
