insert into public.lexicon
(word,lemma,pos,definition,example,difficulty,frequency_rank,source,source_url)
select * from (values
('arbre','arbre','nom','Végétal ligneux possédant un tronc et des branches.','Le vieux chêne est un arbre remarquable.',1,1,'Le Salon starter lexicon',NULL),
('chemin','chemin','nom','Voie permettant de se déplacer d’un lieu à un autre.','Nous suivons un chemin à travers la forêt.',1,2,'Le Salon starter lexicon',NULL),
('lumière','lumière','nom','Rayonnement visible qui permet de voir les objets.','La lumière du matin traverse les rideaux.',1,3,'Le Salon starter lexicon',NULL),
('silence','silence','nom','Absence ou forte diminution de bruit.','Un profond silence règne dans la salle.',1,4,'Le Salon starter lexicon',NULL),
('rivière','rivière','nom','Cours d’eau naturel qui se jette dans un autre cours d’eau.','La rivière traverse le village.',1,5,'Le Salon starter lexicon',NULL),
('souvenir','souvenir','nom','Image ou idée conservée en mémoire.','Ce parfum réveille un ancien souvenir.',1,6,'Le Salon starter lexicon',NULL),
('effort','effort','nom','Action énergique entreprise pour atteindre un résultat.','Son effort régulier finit par payer.',1,7,'Le Salon starter lexicon',NULL),
('doute','doute','nom','État d’incertitude à propos de quelque chose.','Un doute subsiste sur la date exacte.',1,8,'Le Salon starter lexicon',NULL),
('progrès','progrès','nom','Évolution vers un état jugé meilleur.','Les progrès sont visibles après quelques semaines.',1,9,'Le Salon starter lexicon',NULL),
('habitude','habitude','nom','Comportement acquis par répétition.','Lire chaque soir est devenu une habitude.',1,10,'Le Salon starter lexicon',NULL),
('enjeu','enjeu','nom','Ce qui peut être gagné, perdu ou décidé dans une situation.','La sécurité constitue un enjeu majeur.',2,11,'Le Salon starter lexicon',NULL),
('démarche','démarche','nom','Manière organisée d’agir pour atteindre un objectif.','La démarche scientifique repose sur des vérifications.',2,12,'Le Salon starter lexicon',NULL),
('ébauche','ébauche','nom','Première forme encore incomplète d’un travail.','Il présente une ébauche de son projet.',2,13,'Le Salon starter lexicon',NULL),
('repère','repère','nom','Élément servant à s’orienter ou à se situer.','Le clocher est un bon repère dans la ville.',2,14,'Le Salon starter lexicon',NULL),
('nuance','nuance','nom','Différence légère entre deux idées ou deux aspects.','Cette nuance change le sens de la phrase.',2,15,'Le Salon starter lexicon',NULL),
('contrainte','contrainte','nom','Obligation ou limite qui réduit les possibilités d’action.','Le délai constitue une contrainte importante.',2,16,'Le Salon starter lexicon',NULL),
('cohérence','cohérence','nom','Accord logique entre plusieurs éléments.','Le raisonnement gagne en cohérence.',2,17,'Le Salon starter lexicon',NULL),
('ampleur','ampleur','nom','Importance ou étendue d’un phénomène.','On mesure encore mal l’ampleur des dégâts.',2,18,'Le Salon starter lexicon',NULL),
('essor','essor','nom','Développement rapide et important.','Le secteur connaît un essor remarquable.',3,19,'Le Salon starter lexicon',NULL),
('lacune','lacune','nom','Absence ou manque dans un ensemble de connaissances.','Cette étude comporte encore quelques lacunes.',3,20,'Le Salon starter lexicon',NULL),
('paradoxe','paradoxe','nom','Situation ou idée qui semble contraire à la logique attendue.','Ce résultat constitue un paradoxe apparent.',3,21,'Le Salon starter lexicon',NULL),
('prémisse','prémisse','nom','Proposition de départ sur laquelle s’appuie un raisonnement.','La conclusion dépend de la validité de la prémisse.',3,22,'Le Salon starter lexicon',NULL),
('dilemme','dilemme','nom','Choix difficile entre plusieurs possibilités.','Il fait face à un véritable dilemme.',3,23,'Le Salon starter lexicon',NULL),
('conjecture','conjecture','nom','Hypothèse fondée sur des indices mais non démontrée.','Les chercheurs testent cette conjecture.',4,24,'Le Salon starter lexicon',NULL),
('subterfuge','subterfuge','nom','Moyen détourné utilisé pour parvenir à ses fins.','Il a utilisé un subterfuge pour éviter la question.',4,25,'Le Salon starter lexicon',NULL),
('marcher','marcher','verbe','Se déplacer à pied en posant successivement les pieds au sol.','Nous aimons marcher le long du canal.',1,26,'Le Salon starter lexicon',NULL),
('observer','observer','verbe','Regarder attentivement afin de remarquer des détails.','Elle observe le ciel avant l’orage.',1,27,'Le Salon starter lexicon',NULL),
('comprendre','comprendre','verbe','Saisir le sens ou le fonctionnement de quelque chose.','Il cherche à comprendre le problème.',1,28,'Le Salon starter lexicon',NULL),
('choisir','choisir','verbe','Retenir une possibilité parmi plusieurs.','Tu dois choisir une seule réponse.',1,29,'Le Salon starter lexicon',NULL),
('apprendre','apprendre','verbe','Acquérir une connaissance ou une compétence.','Elle apprend de nouveaux mots chaque jour.',1,30,'Le Salon starter lexicon',NULL),
('améliorer','améliorer','verbe','Rendre meilleur ou plus satisfaisant.','Nous voulons améliorer l’interface.',1,31,'Le Salon starter lexicon',NULL),
('prévoir','prévoir','verbe','Envisager à l’avance ce qui peut se produire.','Il faut prévoir assez de temps.',2,32,'Le Salon starter lexicon',NULL),
('soutenir','soutenir','verbe','Maintenir, aider ou défendre quelque chose ou quelqu’un.','Ces données soutiennent l’hypothèse.',2,33,'Le Salon starter lexicon',NULL),
('évaluer','évaluer','verbe','Apprécier la valeur, l’importance ou la qualité de quelque chose.','Le professeur évalue la réponse.',2,34,'Le Salon starter lexicon',NULL),
('résoudre','résoudre','verbe','Trouver une solution à un problème.','Ils tentent de résoudre cette difficulté.',2,35,'Le Salon starter lexicon',NULL),
('distinguer','distinguer','verbe','Reconnaître une différence entre plusieurs éléments.','Il faut distinguer les deux notions.',2,36,'Le Salon starter lexicon',NULL),
('susciter','susciter','verbe','Faire naître une réaction, un sentiment ou un phénomène.','Cette découverte suscite beaucoup d’intérêt.',3,37,'Le Salon starter lexicon',NULL),
('atténuer','atténuer','verbe','Rendre moins fort, moins intense ou moins marqué.','Les rideaux atténuent la lumière.',3,38,'Le Salon starter lexicon',NULL),
('concilier','concilier','verbe','Rendre compatibles des éléments qui semblaient opposés.','Il faut concilier rapidité et précision.',3,39,'Le Salon starter lexicon',NULL),
('étayer','étayer','verbe','Renforcer une affirmation à l’aide d’arguments ou de preuves.','Ces chiffres étayent son analyse.',3,40,'Le Salon starter lexicon',NULL),
('nuancer','nuancer','verbe','Apporter des distinctions qui rendent une affirmation moins absolue.','Elle nuance son jugement après discussion.',3,41,'Le Salon starter lexicon',NULL),
('préconiser','préconiser','verbe','Recommander une action ou une solution.','Le rapport préconise plusieurs améliorations.',3,42,'Le Salon starter lexicon',NULL),
('éluder','éluder','verbe','Éviter habilement de répondre ou d’aborder une difficulté.','Il élude la question la plus délicate.',4,43,'Le Salon starter lexicon',NULL),
('corroborer','corroborer','verbe','Confirmer une information par d’autres éléments concordants.','Les mesures corroborent les premiers résultats.',4,44,'Le Salon starter lexicon',NULL),
('inférer','inférer','verbe','Déduire une conclusion à partir d’indices ou de prémisses.','On peut inférer cette propriété des observations.',4,45,'Le Salon starter lexicon',NULL),
('circonscrire','circonscrire','verbe','Délimiter précisément l’étendue d’un sujet ou d’un problème.','L’étude cherche à circonscrire les causes possibles.',4,46,'Le Salon starter lexicon',NULL),
('préjuger','préjuger','verbe','Former un jugement avant de disposer de tous les éléments.','Il ne faut pas préjuger du résultat.',4,47,'Le Salon starter lexicon',NULL),
('discerner','discerner','verbe','Percevoir ou reconnaître avec finesse.','Elle parvient à discerner une différence subtile.',4,48,'Le Salon starter lexicon',NULL),
('s’affranchir','s’affranchir','verbe','Se libérer d’une contrainte ou d’une dépendance.','Le procédé permet de s’affranchir de cette limitation.',5,49,'Le Salon starter lexicon',NULL),
('subordonner','subordonner','verbe','Faire dépendre une chose d’une autre.','La décision est subordonnée à l’accord final.',5,50,'Le Salon starter lexicon',NULL),
('simple','simple','adjectif','Qui est facile à comprendre ou composé de peu d’éléments.','La méthode reste simple à utiliser.',1,51,'Le Salon starter lexicon',NULL),
('rapide','rapide','adjectif','Qui se fait ou se déplace en peu de temps.','Le calcul est rapide.',1,52,'Le Salon starter lexicon',NULL),
('utile','utile','adjectif','Qui peut servir à atteindre un but ou répondre à un besoin.','Ce raccourci est très utile.',1,53,'Le Salon starter lexicon',NULL),
('calme','calme','adjectif','Qui est paisible et peu agité.','La mer est calme ce matin.',1,54,'Le Salon starter lexicon',NULL),
('précis','précis','adjectif','Qui est défini avec exactitude et peu d’ambiguïté.','Donne une réponse précise.',1,55,'Le Salon starter lexicon',NULL),
('fiable','fiable','adjectif','Sur lequel on peut raisonnablement compter.','Cette source paraît fiable.',2,56,'Le Salon starter lexicon',NULL),
('pertinent','pertinent','adjectif','Qui convient bien au sujet ou à la situation.','Son exemple est particulièrement pertinent.',2,57,'Le Salon starter lexicon',NULL),
('cohérent','cohérent','adjectif','Dont les éléments s’accordent logiquement entre eux.','Le plan est cohérent avec l’objectif.',2,58,'Le Salon starter lexicon',NULL),
('ambigu','ambigu','adjectif','Qui peut recevoir plusieurs interprétations.','La formulation reste ambiguë.',2,59,'Le Salon starter lexicon',NULL),
('durable','durable','adjectif','Qui peut se maintenir longtemps ou limiter son impact futur.','Ils recherchent une solution durable.',2,60,'Le Salon starter lexicon',NULL),
('plausible','plausible','adjectif','Qui paraît pouvoir être vrai ou raisonnable.','Cette explication est plausible.',3,61,'Le Salon starter lexicon',NULL),
('rigoureux','rigoureux','adjectif','Qui respecte des règles précises et exigeantes.','L’analyse doit rester rigoureuse.',3,62,'Le Salon starter lexicon',NULL),
('subtil','subtil','adjectif','Qui présente des distinctions fines et parfois difficiles à percevoir.','Le texte contient une opposition subtile.',3,63,'Le Salon starter lexicon',NULL),
('exhaustif','exhaustif','adjectif','Qui cherche à traiter tous les éléments d’un sujet.','Le rapport vise un inventaire exhaustif.',3,64,'Le Salon starter lexicon',NULL),
('tangible','tangible','adjectif','Qui peut être constaté de manière concrète.','Les premiers bénéfices deviennent tangibles.',3,65,'Le Salon starter lexicon',NULL),
('lacunaire','lacunaire','adjectif','Qui comporte des manques ou des omissions.','Les données disponibles restent lacunaires.',4,66,'Le Salon starter lexicon',NULL),
('fallacieux','fallacieux','adjectif','Qui paraît valable mais repose sur un raisonnement trompeur.','Cet argument est fallacieux.',4,67,'Le Salon starter lexicon',NULL),
('parcimonieux','parcimonieux','adjectif','Qui emploie le minimum nécessaire de moyens ou d’hypothèses.','Le modèle le plus parcimonieux est privilégié.',4,68,'Le Salon starter lexicon',NULL),
('intrinsèque','intrinsèque','adjectif','Qui appartient à la nature propre d’une chose.','La difficulté est intrinsèque au problème.',4,69,'Le Salon starter lexicon',NULL),
('contingent','contingent','adjectif','Qui dépend des circonstances et pourrait être autrement.','Ce résultat est contingent au contexte expérimental.',5,70,'Le Salon starter lexicon',NULL),
('souvent','souvent','adverbe','À de nombreuses reprises ou avec une fréquence élevée.','Il vient souvent travailler ici.',1,71,'Le Salon starter lexicon',NULL),
('parfois','parfois','adverbe','À certains moments, mais pas toujours.','Elle hésite parfois avant de répondre.',1,72,'Le Salon starter lexicon',NULL),
('rapidement','rapidement','adverbe','D’une manière rapide ou en peu de temps.','Le niveau augmente rapidement.',1,73,'Le Salon starter lexicon',NULL),
('clairement','clairement','adverbe','D’une manière facile à comprendre ou à percevoir.','Explique clairement ton raisonnement.',1,74,'Le Salon starter lexicon',NULL),
('presque','presque','adverbe','À peu de chose près, sans atteindre complètement le résultat.','Le travail est presque terminé.',1,75,'Le Salon starter lexicon',NULL),
('davantage','davantage','adverbe','En plus grande quantité ou à un degré supérieur.','Il souhaite apprendre davantage.',2,76,'Le Salon starter lexicon',NULL),
('néanmoins','néanmoins','adverbe','Malgré ce qui vient d’être dit.','Le résultat est imparfait, néanmoins il reste utile.',2,77,'Le Salon starter lexicon',NULL),
('progressivement','progressivement','adverbe','D’une manière graduelle, par étapes.','La difficulté augmente progressivement.',2,78,'Le Salon starter lexicon',NULL),
('précisément','précisément','adverbe','Avec exactitude ou pour insister sur un point déterminé.','C’est précisément ce détail qui compte.',2,79,'Le Salon starter lexicon',NULL),
('globalement','globalement','adverbe','En considérant l’ensemble plutôt que les détails.','Globalement, les résultats sont satisfaisants.',2,80,'Le Salon starter lexicon',NULL)
) as v(word,lemma,pos,definition,example,difficulty,frequency_rank,source,source_url)
where not exists (
  select 1 from public.lexicon l where lower(l.word)=lower(v.word) and l.definition=v.definition
);
