-- Complete production-aligned LexiMind corpus metadata and quality observability.
alter table public.lexicon add column if not exists native_score real;
alter table public.lexicon add column if not exists prevalence real;
alter table public.lexicon add column if not exists content_status text not null default 'ready'
 check (content_status in ('candidate','ready','hidden'));
alter table public.lexicon alter column definition drop not null;
create index if not exists lexicon_native_discovery_idx on public.lexicon(content_status,difficulty,native_score desc,frequency_rank);

create table if not exists public.lexicon_sources(
 key text primary key,title text not null,url text not null,license text not null,attribution text,updated_at timestamptz not null default now()
);
alter table public.lexicon_sources enable row level security;
drop policy if exists "public lexicon sources read" on public.lexicon_sources;
create policy "public lexicon sources read" on public.lexicon_sources for select using(true);

insert into public.lexicon_sources(key,title,url,license,attribution) values
('lexique4','Lexique 4','https://www.lexique.org/','CC BY-SA 4.0','New, Pallier, Schalchli, Bourgin & Gimenes (2026)'),
('wiktionary-fr','Wiktionnaire français','https://fr.wiktionary.org/','CC BY-SA','Contributeurs du Wiktionnaire')
on conflict(key) do update set title=excluded.title,url=excluded.url,license=excluded.license,attribution=excluded.attribution,updated_at=now();

create table if not exists public.lexicon_import_runs(
 id bigint generated by default as identity primary key,
 source_key text not null references public.lexicon_sources(key),
 started_at timestamptz not null default now(),finished_at timestamptz,
 candidates integer not null default 0,ready integer not null default 0,rejected integer not null default 0,notes text
);
alter table public.lexicon_import_runs enable row level security;

create or replace function public.lexicon_quality()
returns jsonb language sql stable security invoker set search_path='' as $$
select jsonb_build_object('total',count(*),'ready',count(*) filter(where content_status='ready'),'candidates',count(*) filter(where content_status='candidate'),'hidden',count(*) filter(where content_status='hidden'),'advanced_ready',count(*) filter(where content_status='ready' and difficulty>=4),'missing_definition',count(*) filter(where content_status='ready' and nullif(btrim(definition),'') is null),'avg_native_score',round(coalesce(avg(native_score) filter(where native_score is not null),0)::numeric,1)) from public.lexicon $$;
grant execute on function public.lexicon_quality() to authenticated;
